# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='communicationsapi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\x12\x11\x63ommunicationsapi\"\x1c\n\x07\x43hannel\x12\x11\n\tchannelId\x18\x01 \x01(\t\"\n\n\x08NoParams\"\x91\x02\n\x0cNotification\x12>\n\x04type\x18\x01 \x01(\x0e\x32\x30.communicationsapi.Notification.NotificationType\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xaf\x01\n\x10NotificationType\x12\x16\n\x12INVITATION_TO_ROOM\x10\x00\x12\x1f\n\x1bINVITATION_TO_ROOM_RESPONSE\x10\x01\x12\x1a\n\x16\x41UTHENTICATION_REQUEST\x10\x02\x12\x1b\n\x17\x41UTHENTICATION_RESPONSE\x10\x03\x12\x0f\n\x0bNEW_MESSAGE\x10\x04\x12\x18\n\x14NEW_MESSAGE_RESPONSE\x10\x05\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0ePublishPayload\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"^\n\x07Payload\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0f\n\x02to\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\r\n\x05seqno\x18\x04 \x01(\x0c\x12\x10\n\x08topicIDs\x18\x05 \x03(\tB\x05\n\x03_to2\x9a\x03\n\x11\x43ommunicationsApi\x12G\n\x0bPingChannel\x12\x1b.communicationsapi.NoParams\x1a\x1b.communicationsapi.Response\x12]\n\x1b\x43onnectToCommunicationsNode\x12\x1b.communicationsapi.NoParams\x1a\x1f.communicationsapi.Notification0\x01\x12L\n\x10\x45ndCommunication\x12\x1b.communicationsapi.NoParams\x1a\x1b.communicationsapi.Response\x12I\n\x07Publish\x12!.communicationsapi.PublishPayload\x1a\x1b.communicationsapi.Response\x12\x44\n\tSubscribe\x12\x1a.communicationsapi.Channel\x1a\x1b.communicationsapi.Responseb\x06proto3'
)



_NOTIFICATION_NOTIFICATIONTYPE = _descriptor.EnumDescriptor(
  name='NotificationType',
  full_name='communicationsapi.Notification.NotificationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVITATION_TO_ROOM', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVITATION_TO_ROOM_RESPONSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTHENTICATION_REQUEST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTHENTICATION_RESPONSE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEW_MESSAGE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEW_MESSAGE_RESPONSE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=173,
  serialized_end=348,
)
_sym_db.RegisterEnumDescriptor(_NOTIFICATION_NOTIFICATIONTYPE)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='communicationsapi.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channelId', full_name='communicationsapi.Channel.channelId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=60,
)


_NOPARAMS = _descriptor.Descriptor(
  name='NoParams',
  full_name='communicationsapi.NoParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=72,
)


_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='communicationsapi.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='communicationsapi.Notification.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='communicationsapi.Notification.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NOTIFICATION_NOTIFICATIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=348,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='communicationsapi.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='communicationsapi.Response.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='communicationsapi.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=394,
)


_PUBLISHPAYLOAD = _descriptor.Descriptor(
  name='PublishPayload',
  full_name='communicationsapi.PublishPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='communicationsapi.PublishPayload.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='communicationsapi.PublishPayload.message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=444,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='communicationsapi.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='communicationsapi.Payload.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to', full_name='communicationsapi.Payload.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='communicationsapi.Payload.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seqno', full_name='communicationsapi.Payload.seqno', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topicIDs', full_name='communicationsapi.Payload.topicIDs', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_to', full_name='communicationsapi.Payload._to',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=446,
  serialized_end=540,
)

_NOTIFICATION.fields_by_name['type'].enum_type = _NOTIFICATION_NOTIFICATIONTYPE
_NOTIFICATION_NOTIFICATIONTYPE.containing_type = _NOTIFICATION
_PAYLOAD.oneofs_by_name['_to'].fields.append(
  _PAYLOAD.fields_by_name['to'])
_PAYLOAD.fields_by_name['to'].containing_oneof = _PAYLOAD.oneofs_by_name['_to']
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
DESCRIPTOR.message_types_by_name['NoParams'] = _NOPARAMS
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['PublishPayload'] = _PUBLISHPAYLOAD
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:communicationsapi.Channel)
  })
_sym_db.RegisterMessage(Channel)

NoParams = _reflection.GeneratedProtocolMessageType('NoParams', (_message.Message,), {
  'DESCRIPTOR' : _NOPARAMS,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:communicationsapi.NoParams)
  })
_sym_db.RegisterMessage(NoParams)

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATION,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:communicationsapi.Notification)
  })
_sym_db.RegisterMessage(Notification)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:communicationsapi.Response)
  })
_sym_db.RegisterMessage(Response)

PublishPayload = _reflection.GeneratedProtocolMessageType('PublishPayload', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHPAYLOAD,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:communicationsapi.PublishPayload)
  })
_sym_db.RegisterMessage(PublishPayload)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:communicationsapi.Payload)
  })
_sym_db.RegisterMessage(Payload)



_COMMUNICATIONSAPI = _descriptor.ServiceDescriptor(
  name='CommunicationsApi',
  full_name='communicationsapi.CommunicationsApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=543,
  serialized_end=953,
  methods=[
  _descriptor.MethodDescriptor(
    name='PingChannel',
    full_name='communicationsapi.CommunicationsApi.PingChannel',
    index=0,
    containing_service=None,
    input_type=_NOPARAMS,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectToCommunicationsNode',
    full_name='communicationsapi.CommunicationsApi.ConnectToCommunicationsNode',
    index=1,
    containing_service=None,
    input_type=_NOPARAMS,
    output_type=_NOTIFICATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndCommunication',
    full_name='communicationsapi.CommunicationsApi.EndCommunication',
    index=2,
    containing_service=None,
    input_type=_NOPARAMS,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Publish',
    full_name='communicationsapi.CommunicationsApi.Publish',
    index=3,
    containing_service=None,
    input_type=_PUBLISHPAYLOAD,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='communicationsapi.CommunicationsApi.Subscribe',
    index=4,
    containing_service=None,
    input_type=_CHANNEL,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMUNICATIONSAPI)

DESCRIPTOR.services_by_name['CommunicationsApi'] = _COMMUNICATIONSAPI

# @@protoc_insertion_point(module_scope)
